/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ReqDAO;
import java.awt.Toolkit;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Dadoss12;
import model.Dadoss1210;

/**
 *
 * @author giovane.oliveira
 */
public class main extends javax.swing.JFrame {

    static boolean checkbox12, checkbox1210;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaS12 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela1210 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        op12 = new javax.swing.JCheckBox();
        op1210 = new javax.swing.JCheckBox();
        dataInicial = new javax.swing.JFormattedTextField();
        dataFinal = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        te2valor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf1valmerc = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf1baseins = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf1inss = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        te5valor = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf1inss2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf1valsest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("XML e-Social versão S-1.0 (Autônomos)");

        jLabel2.setText("Data Inicial");

        jLabel3.setText("Data Final");

        TabelaS12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "E2_FORNECE", "E2_NOMFOR", "E2_VALOR", "F1_DOC", "F1_VALMERC", "F1_BASEINS", "F1_VALSEST", "FI_INSS", "E2_EMISSAO", "E2_VENCREA", "C9V_ID", "FI_FILIAL", "ideDmDev", "C9V_NIS", "C9V_CPF", "PERAPUR", "DT_NASC", "CBO", "DT_NASC_A2", "PIS_A2", "CPF_A2", "A2_NOME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaS12);
        if (TabelaS12.getColumnModel().getColumnCount() > 0) {
            TabelaS12.getColumnModel().getColumn(0).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(1).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(2).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(3).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(4).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(5).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(6).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(7).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(8).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(9).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(10).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(12).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(13).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(14).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(15).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(16).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(17).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(18).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(19).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(20).setPreferredWidth(100);
            TabelaS12.getColumnModel().getColumn(21).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("S-1200");

        tabela1210.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PERIODO", "C9V_CPF", "DT_BAIXA", "E5_VALOR", "EMISSAO", "F1_INSS", "E2_FORNECE", "E2_NOMFOR", "NUMDOC", "ideDmDev"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela1210);
        if (tabela1210.getColumnModel().getColumnCount() > 0) {
            tabela1210.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabela1210.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabela1210.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabela1210.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabela1210.getColumnModel().getColumn(4).setPreferredWidth(100);
            tabela1210.getColumnModel().getColumn(5).setPreferredWidth(100);
            tabela1210.getColumnModel().getColumn(6).setPreferredWidth(100);
            tabela1210.getColumnModel().getColumn(7).setPreferredWidth(200);
            tabela1210.getColumnModel().getColumn(8).setPreferredWidth(100);
            tabela1210.getColumnModel().getColumn(9).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setText("Gerar XML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        op12.setText("S-1200");
        op12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op12ActionPerformed(evt);
            }
        });

        op1210.setText("S-1210");
        op1210.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1210ActionPerformed(evt);
            }
        });

        try {
            dataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            dataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("S-1210");

        jLabel6.setText("TOTALIZADORES:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("E2_VALOR:");

        te2valor.setText("00.00");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("F1_VALMERC:");

        tf1valmerc.setText("00.00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("F1_BASEINS:");

        tf1baseins.setText("00.00");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("F1_INSS:");

        tf1inss.setText("00.00");

        jLabel8.setText("TOTALIZADORES:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("E5_VALOR:");

        te5valor.setText("00.00");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("F1_INSS:");

        tf1inss2.setText("00.00");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("F1_VALSEST:");

        tf1valsest.setText("00.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(te2valor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf1valmerc)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf1baseins)
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf1inss)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf1valsest))
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))))))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(op12)
                                        .addGap(18, 18, 18)
                                        .addComponent(op1210))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jButton2))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(te5valor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf1inss2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(op12)
                    .addComponent(op1210)
                    .addComponent(dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(te2valor)
                    .addComponent(jLabel9)
                    .addComponent(tf1valmerc)
                    .addComponent(jLabel11)
                    .addComponent(tf1baseins)
                    .addComponent(jLabel13)
                    .addComponent(tf1inss)
                    .addComponent(jLabel15)
                    .addComponent(tf1valsest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(te5valor)
                    .addComponent(jLabel14)
                    .addComponent(tf1inss2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double e2valor = 0.0,f1valmerc = 0.0,f1baseins = 0.0,f1inss = 0.0, e5valor = 0.0, f1inss2 = 0.0, f1valsest = 0.0; //totalizadores
        DecimalFormat df = new DecimalFormat("0.00");
        
        if (dataInicial.getText().replace("/", "").trim().isEmpty() || dataFinal.getText().replace("/", "").trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Informe a data inicial e final");

        } else {

            ReqDAO dao = new ReqDAO();
            List<Dadoss12> lista = dao.consultarDadosS12(dataInicial.getText(), dataFinal.getText());
            DefaultTableModel dadoss12 = (DefaultTableModel) TabelaS12.getModel();
            TabelaS12.setAutoResizeMode(TabelaS12.AUTO_RESIZE_OFF);
            dadoss12.setNumRows(0);
            for (Dadoss12 c : lista) {

                e2valor = e2valor + Double.parseDouble(c.getE2_VALOR().trim());
                f1valmerc = f1valmerc + Double.parseDouble(c.getF1_VALMERC());
                f1baseins = f1baseins + Double.parseDouble(c.getF1_BASEINS().trim());
                f1inss = f1inss + Double.parseDouble(c.getF1_INSS().trim());
                 f1valsest = f1valsest + Double.parseDouble(c.getF1_VALSEST().trim());
                dadoss12.addRow(new Object[]{
                    c.getE2_FORNECE(),
                    c.getE2_NOMFOR(),
                    c.getE2_VALOR(),
                    c.getF1_DOC(),
                    c.getF1_VALMERC(),
                    c.getF1_BASEINS(),
                    c.getF1_VALSEST(),
                    c.getF1_INSS(),
                    c.getE2_EMISSAO(),
                    c.getE2_VENCREA(),
                    c.getC9V_ID(),
                    c.getF1_FILIAL(),
                    c.getIdeDmDev(),
                    c.getC9_NIS(),
                    c.getC9V_CPF(),
                    c.getPERAPUR(),
                    c.getDT_NASC(),
                    c.getCBO(),
                    c.getDT_NASC_A2(),
                    c.getPIS_A2(),
                    c.getCPF_A2(),
                    c.getA2_NOME()
                });
            }
       te2valor.setText("" + String.valueOf(df.format(e2valor)));
        tf1valmerc.setText("" + String.valueOf(df.format(f1valmerc)));
         tf1baseins.setText("" + String.valueOf(df.format(f1baseins)));
          tf1inss.setText("" + String.valueOf(df.format(f1inss)));
           tf1valsest.setText("" + String.valueOf(df.format(f1valsest)));
            ReqDAO obj = new ReqDAO();
            List<Dadoss1210> lista2 = obj.consultarDadosS1210(dataInicial.getText(), dataFinal.getText());
            DefaultTableModel dadoss1210 = (DefaultTableModel) tabela1210.getModel();
            tabela1210.setAutoResizeMode(tabela1210.AUTO_RESIZE_OFF);
            dadoss1210.setNumRows(0);
            for (Dadoss1210 c : lista2) {
            e5valor = e5valor + Double.parseDouble(c.getE5_VALOR().trim());
            f1inss2 = f1inss2 + Double.parseDouble(c.getF1_INSS().trim());
                dadoss1210.addRow(new Object[]{
                    c.getPERIODO(),
                    c.getC9V_CPF(),
                    c.getDT_BAIXA(),
                    c.getE5_VALOR(),
                    c.getEMISSAO(),
                    c.getF1_INSS(),
                    c.getE2_FORNECE(),
                    c.getE2_NOMFOR(),
                    c.getNUMDOC(),
                    c.getIdeDmDev()

                });
            }
  te5valor.setText("" + String.valueOf(df.format(e5valor)));
  tf1inss2.setText("" + String.valueOf(df.format(f1inss2)));
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int n = 1;
        String TipoAmbiente;
        String IndicadorRetificacao;
        if (dataInicial.getText().replace("/", "").trim().isEmpty() || dataFinal.getText().replace("/", "").trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Informe a data inicial e final");
            n = 0;

        } else {

            ReqDAO obj = new ReqDAO();
            List<Dadoss12> lista = obj.consultarDadosS12(dataInicial.getText(), dataFinal.getText());
            List<Dadoss1210> lista2 = obj.consultarDadosS1210(dataInicial.getText(), dataFinal.getText());

            if (checkbox12 == true && checkbox1210 == true) {

                do {

                    IndicadorRetificacao = JOptionPane.showInputDialog("Informe 1 (OFICIAL) ou 2 (PRÉ-PRODUÇÃO) para o Indicador Retificação:");
                    TipoAmbiente = JOptionPane.showInputDialog("Informe 1 (OFICIAL) ou 2(PRÉ-PRODUÇÃO) para o Tipo de Ambiente:");
               } while (!TipoAmbiente.equals("1") && !IndicadorRetificacao.equals("1") && !TipoAmbiente.equals("2") && !IndicadorRetificacao.equals("2"));

                for (Dadoss12 c : lista) {

                    try {
                        obj.gerarxml12(c, IndicadorRetificacao, TipoAmbiente);
                    } catch (IOException ex) {
                        n = 0;
                        Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

                for (Dadoss1210 d : lista2) {

                    try {
                        obj.gerarxml1210(d, IndicadorRetificacao, TipoAmbiente);

                    } catch (IOException ex) {
                        n = 0;
                        Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } else if (checkbox12 == true && checkbox1210 == false) {
                do {

                    IndicadorRetificacao = JOptionPane.showInputDialog("Informe 1 (OFICIAL) ou 2 (PRÉ-PRODUÇÃO) para o Indicador Retificação:");
                    TipoAmbiente = JOptionPane.showInputDialog("Informe 1 (OFICIAL) ou 2(PRÉ-PRODUÇÃO) para o Tipo de Ambiente:");
                } while (!TipoAmbiente.equals("1") && !IndicadorRetificacao.equals("1") && !TipoAmbiente.equals("2") && !IndicadorRetificacao.equals("2"));

                for (Dadoss12 c : lista) {

                    try {
                        obj.gerarxml12(c, IndicadorRetificacao, TipoAmbiente);

                    } catch (IOException ex) {
                        n = 0;
                        Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } else if (checkbox12 == false && checkbox1210 == true) {
                do {

                    IndicadorRetificacao = JOptionPane.showInputDialog("Informe 1 (OFICIAL) ou 2 (PRÉ-PRODUÇÃO) para o Indicador Retificação:");
                    TipoAmbiente = JOptionPane.showInputDialog("Informe 1 (OFICIAL) ou 2(PRÉ-PRODUÇÃO) para o Tipo de Ambiente:");
                    JOptionPane.showMessageDialog(null, "Aqui " + TipoAmbiente.replaceAll("\\s+", ""));
                } while (!TipoAmbiente.equals("1") && !IndicadorRetificacao.equals("1") && !TipoAmbiente.equals("2") && !IndicadorRetificacao.equals("2"));

                for (Dadoss1210 d : lista2) {

                    try {
                        obj.gerarxml1210(d, IndicadorRetificacao, TipoAmbiente);

                    } catch (IOException ex) {
                        n = 0;
                        Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } else {

                JOptionPane.showMessageDialog(null, "Marque alguma das opções para gerar o xml");
                n = 0;
            }

            /*  try {
            obj.gerarxml("teste");
        
        }

       
        } catch (IOException ex) {
          JOptionPane.showMessageDialog(null,"Erro: " + ex);
        }*/
        }

        if (n == 1) {

            JOptionPane.showMessageDialog(null, "Arquivo gerado com sucesso");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void op12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op12ActionPerformed
        // TODO add your handling code here:

        JCheckBox cbLog = (JCheckBox) evt.getSource();
        if (cbLog.isSelected()) {
            // System.out.println("Logging is enabled");
            checkbox12 = true;
        } else {
            checkbox1210 = false;
//System.out.println("Logging is disabled");
        }


    }//GEN-LAST:event_op12ActionPerformed

    private void op1210ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1210ActionPerformed
        // TODO add your handling code here:
        JCheckBox cbLog = (JCheckBox) evt.getSource();
        if (cbLog.isSelected()) {
            checkbox1210 = true;
//System.out.println("Logging is enabled");
        } else {
            checkbox12 = false;
//System.out.println("Logging is disabled");
        }


    }//GEN-LAST:event_op1210ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaS12;
    private javax.swing.JFormattedTextField dataFinal;
    private javax.swing.JFormattedTextField dataInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox op12;
    private javax.swing.JCheckBox op1210;
    private javax.swing.JTable tabela1210;
    private javax.swing.JLabel te2valor;
    private javax.swing.JLabel te5valor;
    private javax.swing.JLabel tf1baseins;
    private javax.swing.JLabel tf1inss;
    private javax.swing.JLabel tf1inss2;
    private javax.swing.JLabel tf1valmerc;
    private javax.swing.JLabel tf1valsest;
    // End of variables declaration//GEN-END:variables
}
